//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace WUFT.NET.WorkerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WorkerServiceSoap", Namespace="http://isewebservices.intel.com/WorkerService.asmx")]
    public partial class WorkerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetWorkerDetailByIDSIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWorkerDetailsByIDSIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSignatureAuthorityListByWWIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkerDetailsByMgrWWIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWorkerDetailsByMgrWWIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkerDetailByWWIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWorkerDetailsByWWIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkerDetailByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWorkerDetailsByNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WorkerService() {
            this.Url = global::WUFT.NET.Properties.Settings.Default.WUFT_NET_WorkerService_WorkerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetWorkerDetailByIDSIDCompletedEventHandler GetWorkerDetailByIDSIDCompleted;
        
        /// <remarks/>
        public event GetAllWorkerDetailsByIDSIDCompletedEventHandler GetAllWorkerDetailsByIDSIDCompleted;
        
        /// <remarks/>
        public event GetSignatureAuthorityListByWWIDCompletedEventHandler GetSignatureAuthorityListByWWIDCompleted;
        
        /// <remarks/>
        public event GetWorkerDetailsByMgrWWIDCompletedEventHandler GetWorkerDetailsByMgrWWIDCompleted;
        
        /// <remarks/>
        public event GetAllWorkerDetailsByMgrWWIDCompletedEventHandler GetAllWorkerDetailsByMgrWWIDCompleted;
        
        /// <remarks/>
        public event GetWorkerDetailByWWIDCompletedEventHandler GetWorkerDetailByWWIDCompleted;
        
        /// <remarks/>
        public event GetAllWorkerDetailsByWWIDCompletedEventHandler GetAllWorkerDetailsByWWIDCompleted;
        
        /// <remarks/>
        public event GetWorkerDetailByNameCompletedEventHandler GetWorkerDetailByNameCompleted;
        
        /// <remarks/>
        public event GetAllWorkerDetailsByNameCompletedEventHandler GetAllWorkerDetailsByNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetWorkerDetailByIDSID(string userName, string password, string idsid) {
            object[] results = this.Invoke("GetWorkerDetailByIDSID", new object[] {
                        userName,
                        password,
                        idsid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkerDetailByIDSIDAsync(string userName, string password, string idsid) {
            this.GetWorkerDetailByIDSIDAsync(userName, password, idsid, null);
        }
        
        /// <remarks/>
        public void GetWorkerDetailByIDSIDAsync(string userName, string password, string idsid, object userState) {
            if ((this.GetWorkerDetailByIDSIDOperationCompleted == null)) {
                this.GetWorkerDetailByIDSIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkerDetailByIDSIDOperationCompleted);
            }
            this.InvokeAsync("GetWorkerDetailByIDSID", new object[] {
                        userName,
                        password,
                        idsid}, this.GetWorkerDetailByIDSIDOperationCompleted, userState);
        }
        
        private void OnGetWorkerDetailByIDSIDOperationCompleted(object arg) {
            if ((this.GetWorkerDetailByIDSIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkerDetailByIDSIDCompleted(this, new GetWorkerDetailByIDSIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetAllWorkerDetailsByIDSID", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetAllWorkerDetailsByIDSID(string userName, string password, string idsid) {
            object[] results = this.Invoke("GetAllWorkerDetailsByIDSID", new object[] {
                        userName,
                        password,
                        idsid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByIDSIDAsync(string userName, string password, string idsid) {
            this.GetAllWorkerDetailsByIDSIDAsync(userName, password, idsid, null);
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByIDSIDAsync(string userName, string password, string idsid, object userState) {
            if ((this.GetAllWorkerDetailsByIDSIDOperationCompleted == null)) {
                this.GetAllWorkerDetailsByIDSIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWorkerDetailsByIDSIDOperationCompleted);
            }
            this.InvokeAsync("GetAllWorkerDetailsByIDSID", new object[] {
                        userName,
                        password,
                        idsid}, this.GetAllWorkerDetailsByIDSIDOperationCompleted, userState);
        }
        
        private void OnGetAllWorkerDetailsByIDSIDOperationCompleted(object arg) {
            if ((this.GetAllWorkerDetailsByIDSIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWorkerDetailsByIDSIDCompleted(this, new GetAllWorkerDetailsByIDSIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetSignatureAuthorityListByWWID", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetSignatureAuthorityListByWWID(string userName, string password, string wwid) {
            object[] results = this.Invoke("GetSignatureAuthorityListByWWID", new object[] {
                        userName,
                        password,
                        wwid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetSignatureAuthorityListByWWIDAsync(string userName, string password, string wwid) {
            this.GetSignatureAuthorityListByWWIDAsync(userName, password, wwid, null);
        }
        
        /// <remarks/>
        public void GetSignatureAuthorityListByWWIDAsync(string userName, string password, string wwid, object userState) {
            if ((this.GetSignatureAuthorityListByWWIDOperationCompleted == null)) {
                this.GetSignatureAuthorityListByWWIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSignatureAuthorityListByWWIDOperationCompleted);
            }
            this.InvokeAsync("GetSignatureAuthorityListByWWID", new object[] {
                        userName,
                        password,
                        wwid}, this.GetSignatureAuthorityListByWWIDOperationCompleted, userState);
        }
        
        private void OnGetSignatureAuthorityListByWWIDOperationCompleted(object arg) {
            if ((this.GetSignatureAuthorityListByWWIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSignatureAuthorityListByWWIDCompleted(this, new GetSignatureAuthorityListByWWIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetWorkerDetailsByMgrWWID", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetWorkerDetailsByMgrWWID(string userName, string password, string wwid) {
            object[] results = this.Invoke("GetWorkerDetailsByMgrWWID", new object[] {
                        userName,
                        password,
                        wwid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkerDetailsByMgrWWIDAsync(string userName, string password, string wwid) {
            this.GetWorkerDetailsByMgrWWIDAsync(userName, password, wwid, null);
        }
        
        /// <remarks/>
        public void GetWorkerDetailsByMgrWWIDAsync(string userName, string password, string wwid, object userState) {
            if ((this.GetWorkerDetailsByMgrWWIDOperationCompleted == null)) {
                this.GetWorkerDetailsByMgrWWIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkerDetailsByMgrWWIDOperationCompleted);
            }
            this.InvokeAsync("GetWorkerDetailsByMgrWWID", new object[] {
                        userName,
                        password,
                        wwid}, this.GetWorkerDetailsByMgrWWIDOperationCompleted, userState);
        }
        
        private void OnGetWorkerDetailsByMgrWWIDOperationCompleted(object arg) {
            if ((this.GetWorkerDetailsByMgrWWIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkerDetailsByMgrWWIDCompleted(this, new GetWorkerDetailsByMgrWWIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetAllWorkerDetailsByMgrWWID", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetAllWorkerDetailsByMgrWWID(string userName, string password, string wwid) {
            object[] results = this.Invoke("GetAllWorkerDetailsByMgrWWID", new object[] {
                        userName,
                        password,
                        wwid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByMgrWWIDAsync(string userName, string password, string wwid) {
            this.GetAllWorkerDetailsByMgrWWIDAsync(userName, password, wwid, null);
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByMgrWWIDAsync(string userName, string password, string wwid, object userState) {
            if ((this.GetAllWorkerDetailsByMgrWWIDOperationCompleted == null)) {
                this.GetAllWorkerDetailsByMgrWWIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWorkerDetailsByMgrWWIDOperationCompleted);
            }
            this.InvokeAsync("GetAllWorkerDetailsByMgrWWID", new object[] {
                        userName,
                        password,
                        wwid}, this.GetAllWorkerDetailsByMgrWWIDOperationCompleted, userState);
        }
        
        private void OnGetAllWorkerDetailsByMgrWWIDOperationCompleted(object arg) {
            if ((this.GetAllWorkerDetailsByMgrWWIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWorkerDetailsByMgrWWIDCompleted(this, new GetAllWorkerDetailsByMgrWWIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetWorkerDetailByWWID", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetWorkerDetailByWWID(string userName, string password, string wwid) {
            object[] results = this.Invoke("GetWorkerDetailByWWID", new object[] {
                        userName,
                        password,
                        wwid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkerDetailByWWIDAsync(string userName, string password, string wwid) {
            this.GetWorkerDetailByWWIDAsync(userName, password, wwid, null);
        }
        
        /// <remarks/>
        public void GetWorkerDetailByWWIDAsync(string userName, string password, string wwid, object userState) {
            if ((this.GetWorkerDetailByWWIDOperationCompleted == null)) {
                this.GetWorkerDetailByWWIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkerDetailByWWIDOperationCompleted);
            }
            this.InvokeAsync("GetWorkerDetailByWWID", new object[] {
                        userName,
                        password,
                        wwid}, this.GetWorkerDetailByWWIDOperationCompleted, userState);
        }
        
        private void OnGetWorkerDetailByWWIDOperationCompleted(object arg) {
            if ((this.GetWorkerDetailByWWIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkerDetailByWWIDCompleted(this, new GetWorkerDetailByWWIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetAllWorkerDetailsByWWID", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetAllWorkerDetailsByWWID(string userName, string password, string wwid) {
            object[] results = this.Invoke("GetAllWorkerDetailsByWWID", new object[] {
                        userName,
                        password,
                        wwid});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByWWIDAsync(string userName, string password, string wwid) {
            this.GetAllWorkerDetailsByWWIDAsync(userName, password, wwid, null);
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByWWIDAsync(string userName, string password, string wwid, object userState) {
            if ((this.GetAllWorkerDetailsByWWIDOperationCompleted == null)) {
                this.GetAllWorkerDetailsByWWIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWorkerDetailsByWWIDOperationCompleted);
            }
            this.InvokeAsync("GetAllWorkerDetailsByWWID", new object[] {
                        userName,
                        password,
                        wwid}, this.GetAllWorkerDetailsByWWIDOperationCompleted, userState);
        }
        
        private void OnGetAllWorkerDetailsByWWIDOperationCompleted(object arg) {
            if ((this.GetAllWorkerDetailsByWWIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWorkerDetailsByWWIDCompleted(this, new GetAllWorkerDetailsByWWIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetWorkerDetailByName", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetWorkerDetailByName(string userName, string password, string name) {
            object[] results = this.Invoke("GetWorkerDetailByName", new object[] {
                        userName,
                        password,
                        name});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkerDetailByNameAsync(string userName, string password, string name) {
            this.GetWorkerDetailByNameAsync(userName, password, name, null);
        }
        
        /// <remarks/>
        public void GetWorkerDetailByNameAsync(string userName, string password, string name, object userState) {
            if ((this.GetWorkerDetailByNameOperationCompleted == null)) {
                this.GetWorkerDetailByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkerDetailByNameOperationCompleted);
            }
            this.InvokeAsync("GetWorkerDetailByName", new object[] {
                        userName,
                        password,
                        name}, this.GetWorkerDetailByNameOperationCompleted, userState);
        }
        
        private void OnGetWorkerDetailByNameOperationCompleted(object arg) {
            if ((this.GetWorkerDetailByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkerDetailByNameCompleted(this, new GetWorkerDetailByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://isewebservices.intel.com/WorkerService.asmx?op=GetAllWorkerDetailsByName", RequestNamespace="http://isewebservices.intel.com/WorkerService.asmx", ResponseNamespace="http://isewebservices.intel.com/WorkerService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetAllWorkerDetailsByName(string userName, string password, string name) {
            object[] results = this.Invoke("GetAllWorkerDetailsByName", new object[] {
                        userName,
                        password,
                        name});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByNameAsync(string userName, string password, string name) {
            this.GetAllWorkerDetailsByNameAsync(userName, password, name, null);
        }
        
        /// <remarks/>
        public void GetAllWorkerDetailsByNameAsync(string userName, string password, string name, object userState) {
            if ((this.GetAllWorkerDetailsByNameOperationCompleted == null)) {
                this.GetAllWorkerDetailsByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWorkerDetailsByNameOperationCompleted);
            }
            this.InvokeAsync("GetAllWorkerDetailsByName", new object[] {
                        userName,
                        password,
                        name}, this.GetAllWorkerDetailsByNameOperationCompleted, userState);
        }
        
        private void OnGetAllWorkerDetailsByNameOperationCompleted(object arg) {
            if ((this.GetAllWorkerDetailsByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWorkerDetailsByNameCompleted(this, new GetAllWorkerDetailsByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetWorkerDetailByIDSIDCompletedEventHandler(object sender, GetWorkerDetailByIDSIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkerDetailByIDSIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkerDetailByIDSIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllWorkerDetailsByIDSIDCompletedEventHandler(object sender, GetAllWorkerDetailsByIDSIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWorkerDetailsByIDSIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWorkerDetailsByIDSIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetSignatureAuthorityListByWWIDCompletedEventHandler(object sender, GetSignatureAuthorityListByWWIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSignatureAuthorityListByWWIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSignatureAuthorityListByWWIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetWorkerDetailsByMgrWWIDCompletedEventHandler(object sender, GetWorkerDetailsByMgrWWIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkerDetailsByMgrWWIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkerDetailsByMgrWWIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllWorkerDetailsByMgrWWIDCompletedEventHandler(object sender, GetAllWorkerDetailsByMgrWWIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWorkerDetailsByMgrWWIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWorkerDetailsByMgrWWIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetWorkerDetailByWWIDCompletedEventHandler(object sender, GetWorkerDetailByWWIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkerDetailByWWIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkerDetailByWWIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllWorkerDetailsByWWIDCompletedEventHandler(object sender, GetAllWorkerDetailsByWWIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWorkerDetailsByWWIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWorkerDetailsByWWIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetWorkerDetailByNameCompletedEventHandler(object sender, GetWorkerDetailByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkerDetailByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkerDetailByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllWorkerDetailsByNameCompletedEventHandler(object sender, GetAllWorkerDetailsByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWorkerDetailsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWorkerDetailsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591