name: Auto build WUFT.
on:
  push: 
    branches: 
      - Dev*
jobs:
  job-vm-auto-build-dev-server:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Allow download long file.
        run: git config --system core.longpaths true

      - name: Exact branch.
        uses: actions/checkout@v2
        
      - name: Clean build directory.
        run: if exist Codebuild (rmdir /s/q Codebuild)
        working-directory: ../

      - name: Copy source code to build directory.
        run: xcopy "WUFT" "Codebuild" /s /y /e /i
        working-directory: ../

      - name: Build projects
        run: npm run build
        env:
          CI: ""
          working-directory: ../Codebuild
