
# This is a basic workflow to help you get started with Actions

name: WUFT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Development_Original branch
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: WUFT-Runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo echo STAGE --> %CI_JOB_STAGE%,
          echo MsBuild Path -  %MSBuild%,
          echo building the solution projects...
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe'C:\Karthik\ISET\wuft-development-2023\wuft-development-2023\WUFT.NET\WUFT.NET.csproj /target:clean
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe'C:\Karthik\ISET\wuft-development-2023\wuft-development-2023\WUFT.NET\WUFT.NET.csproj /target:Build
  publish:
     
    # The type of runner that the job will run on
    runs-on: WUFT-Runner
    needs: [build]
    #environment:
      #name: Test environment

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
             echo STAGE --> %CI_JOB_STAGE%
             & 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe'C:\Karthik\ISET\wuft-development-2023\wuft-development-2023\WUFT.NET\WUFT.NET.csproj /t:build /p:outdir=obj\ /p:Configuration=Release /p:Platform="AnyCPU"  

  removing_WebConfig:
      
    # The type of runner that the job will run on
    runs-on: WUFT-Runner
    needs: [publish]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

       #Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
           echo Deleting web.config....
           Remove-Item -Path 

  envirnoment_backup:
      
    # The type of runner that the job will run on
    runs-on: label_emulation_qa
    needs: [removing_WebConfig]
    environment:
      name: backuping files

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

       #Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          $dt = get-date -format "MM-dd-yyyy-hhmmss"
          $currDir = ""
          $bkpDir = ""
          echo $currDir
          echo $bkpDir
          if (-not (Test-Path $bkpDir)) { mkdir $bkpDir }
          xcopy $currDir $bkpDir /E/Y

  deploy_Dev:
      
    # The type of runner that the job will run on
    runs-on: label_emulation_qa
    needs: [envirnoment_backup]
    environment:
      name: Dev environment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

       #Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          $source="C:\Karthik\ISET\wuft-development-2023\wuft-development-2023\WUFT.NET"
          $dest=""
          robocopy $source $dest /E /DCOPY:DAT /R:10 /W:3; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null } 

